; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s2-saola-1]
platform = espressif32
board = esp32-s2-saola-1

framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

lib_deps =
    ;ardnew/STUSB4500@^1.0.3
    sparkfun/SparkFun STUSB4500 @ ^1.1.5
    ;https://github.com/Lawmate/BQ25703A
    ;https://github.com/adityabangde/ESP32-Flasher
    adafruit/Adafruit NeoPixel @ ^1.14.0
    ;xreef/PCF8574 library @ ^2.3.7
    spacehuhn/SimpleCLI @ ^1.1.4
    adafruit/Adafruit INA3221 Library @ ^1.0.1
    sstaub/Ticker @ ^4.4.0
    bodmer/TFT_eSPI @ ^2.5.43
    ;bitbank2/PNGdec @ ^1.1.6
    lvgl/lvgl @ ^9.3.0
    paulstoffregen/XPT2046_Touchscreen @ 0.0.0-alpha+sha.26b691b2c8
    madhephaestus/ESP32Encoder @ ^0.11.8

