; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200


lib_deps =
    ;ardnew/STUSB4500@^1.0.3
    sparkfun/SparkFun STUSB4500 @ ^1.1.5
    https://github.com/Lawmate/BQ25703A
    ;https://github.com/Mala2/BQ28Z610
    adafruit/Adafruit NeoPixel @ ^1.14.0
    ;xreef/PCF8574 library @ ^2.3.7
    fmalpartida/LiquidCrystal @ ^1.5.0
    adafruit/Adafruit MCP23017 Arduino Library @ ^2.3.2
    spacehuhn/SimpleCLI @ ^1.1.4
    